# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: image.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bimage.proto\"I\n\x0cImageRequest\x12\x11\n\timage_ops\x18\x01 \x01(\t\x12\x12\n\nimage_type\x18\x02 \x01(\t\x12\x12\n\nchunk_data\x18\x03 \x01(\x0c\"[\n\x0bImageReturn\x12\x12\n\nimage_type\x18\x01 \x01(\t\x12\x16\n\x0eimg_chunk_data\x18\x02 \x01(\x0c\x12\x10\n\x08\x66ilename\x18\x03 \x01(\t\x12\x0e\n\x06\x65rrors\x18\x04 \x01(\t2C\n\x0eImageProcessor\x12\x31\n\x0cProcessImage\x12\r.ImageRequest\x1a\x0c.ImageReturn\"\x00(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'image_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_IMAGEREQUEST']._serialized_start=15
  _globals['_IMAGEREQUEST']._serialized_end=88
  _globals['_IMAGERETURN']._serialized_start=90
  _globals['_IMAGERETURN']._serialized_end=181
  _globals['_IMAGEPROCESSOR']._serialized_start=183
  _globals['_IMAGEPROCESSOR']._serialized_end=250
# @@protoc_insertion_point(module_scope)
